# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MsgReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=250, null=True)),
                ('user_id', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('discription', models.CharField(blank=True, max_length=250, null=True)),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=250, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=250, null=True)),
            ],
        ),
    ]
